spring:
  application:
    name: fullstack-app
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
